@startuml
header
Last updated: %date()
endheader

title Архитектурные решения


' Definitions
class D1 << (+,limegreen) >>{
Предпосылки/контекст:\nсуществующие решения точка-точка усложняют переиспользование, требуют так же интеграции с Vault, Zabbix, Prometeus
--
Решение: \nиспользовать Gateway для новых интеграций для проверки контрагентов
--
Последствия: \nИзменение существующих интеграций и запись техдолга для прямых интеграций
--
Затрагивемые системы:\nВсе
--
Проект: 
--
Дата: %date()
}

class D5 << (+,limegreen) >>{
Предпосылки/контекст:\nХранение секретов в конечных системах противоречит требованиям ИБ
--
Решение: \nиспользовать Hashicorp Vault для хранения секретов
--
Последствия: \nИзменение текущих механизмов хранения секретов для систем. Техдолг.
--
Затрагивемые системы:\nВсе
--
Проект: 
--
Дата: %date()
}

class D6 << (+,limegreen) >>{
Предпосылки/контекст:\nотсутствие единого мониторинга усложняет обеспечение непрерывности
--
Решение: \nиспользовать централизованный Zabbix для мониторинга
--
Последствия: \nИзменение текущих механизмов мониторинга. Техдолг.
--
Затрагивемые системы:\nВсе
--
Проект: 
--
Дата: %date()
}

class D2 << (X,gray) >>{
Предпосылки/контекст:\nнеобходима проверка контрагентов через Dow Jones в S/4
--
Решение: \nПрямая интеграция с Dow Jones через SAP PI
--
Последствия: \nнет
--
Затрагивемые системы:\n* SAP S/4\n* SAP PI
--
Проект:  [[https://jira.pgk.ru/PRJ1]]
--
Дата: %date()
}

class D3 << (T,orange) >>{
Предпосылки/контекст:\nнеобходима проверка контрагентов через Спарк
--
Решение: \nПрямая интеграция с Спарк Интерфакс
--
Последствия: \nнет
--
Затрагивемые системы:\n* Opentext
--
Проект:  [[https://jira.pgk.ru/PRJ2]]
--
Дата: %date()
}

class D10 << (+,limegreen) >>{
Предпосылки/контекст:\nПрекращение использования ServiceNow
--
Решение: \nЗапрет реализации новых проектов с использованием ServiceNow
--
Последствия: \nнет
--
Затрагивемые системы:\n* ServiceNow
--
Дата: %date()
}

class D11 << (+,limegreen) >>{
Предпосылки/контекст:\nРеализация сервиса консультирования юристов
--
Решение: \nРеализация через Bitrix
--
Последствия: \nнет
--
Затрагивемые системы:\n* Bitrix
--
Проект:  [[https://jira.pgk.ru/PRJ3]]
--
Дата: %date()
}

class D12 << (+,limegreen) >>{
Предпосылки/контекст:\nРеализация сервиса обнаружения опасного поведения
--
Решение: \nРеализация через Bitrix
--
Последствия: \nнет
--
Затрагивемые системы:\n* Bitrix
--
Проект:  [[https://jira.pgk.ru/PRJ5]]
--
Дата: %date()
}

class D21 << (?,lightblue) >>{
Предпосылки/контекст:\nУнификация и переход к сервисной архитектуре
--
Решение: \nРеализация через Gateway
--
Последствия: \nТехдолг
--
Затрагивемые системы:\n* Все
--
Проект:  [[https://jira.pgk.ru/PRJ_XX]]
--
Дата: %date()
}

D2 --> D1 : отменено
'
D3 --> D5 : нарушает
D3 --> D6 : нарушает
'
D12 --> D10 : вызвано
D11 --> D10 : вызвано
D21 --> D1 : расширяет
' Relations

' Legend
legend bottom right
|=|=Описание|
|<#limegreen>+|актуальное действующее решение|
|<#lightblue>?|предложенное решение|
|<#orange>T|временное решение|
|<#gray>X|отменённое решение|
endlegend
@enduml