@startuml
header
Last updated: %date()
endheader

' TODO :: Move header to config
title Архитектурные решения

' TODO :: Move "ADR" prefix to some kind of config
{% for adr in obj%}
class ADR-{{ adr.id }} << ({{ adr.decStatus.mark }}, {{ adr.decStatus.color }}) >>{
' a3.first().__dict__.get('Decision context')
Предпосылки/контекст:\n{{ adr.decContext }}
--
Решение: \n{{ adr.decision }}
--
Последствия: \n{{ adr.effects }}
--
Затрагивемые системы:\n* {{  adr.affectedSolutions }}
--
Проект:  [[{{ adr.projectLink }}]]
--
Дата: {{ adr.adrCreatedAt }}

'{{ adr.influence }}
}
{% endfor %}

' Relations

{% if direction == 1 %}
{% for rel in influence %}
"{{ rel.src_adr.qualifiedID }}" --> "{{ rel.inf_adr.qualifiedID }}" : "{{ rel.influence.description_fwd }}"{% endfor %}
{% else %}
{% for rel in influence %}
"{{ rel.inf_adr.qualifiedID }}" --> "{{ rel.src_adr.qualifiedID }}" : "{{ rel.influence.description_back }}"{% endfor %}
{% endif %}
' End of relations

' Start of legend
legend bottom right
|=|=Описание|
{% for item in legend %}| <#{{ item.color }}>{{ item.mark }}| {{ item.description }}|
{% endfor %}
endlegend
' End of legend
@enduml