@startuml
header
Last updated: %date()
endheader

title Архитектурные решения

' TODO :: Move "ADR" prefix to some kind of config
{% for adr in obj%}
class ADR-{{ adr.id }} << ({{ adr.decStatus.mark }}, {{ adr.decStatus.color }}) >>{
' a3.first().__dict__.get('Decision context')
Предпосылки/контекст:\n{{ adr.decContext }}
--
Решение: \n{{ adr.decision }}
--
Последствия: \n{{ adr.effects }}
--
Затрагивемые системы:\n* {{  adr.affectedSolutions }}
--
Проект:  [[{{ adr.projectLink }}]]
--
Дата: {{ adr.adrCreatedAt }}

'{{ adr.influence }}
}
{% endfor %}

' Relations
'
'{% for adr in obj%}
'    {{ adr.influence }}
'{% endfor %}
legend bottom right
|=|=Описание|
{% for item in legend %}| <#{{ item.color }}>{{ item.mark }}| {{ item.description }}|
{% endfor %}
endlegend
@enduml