# Generated by Django 4.0.5 on 2022-06-11 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adrCreatedAt', models.DateTimeField(auto_now_add=True, db_column='createdAt', help_text='Required. First date of consideration', null=True, verbose_name='When ADR was created')),
                ('Decision context', models.TextField(db_column='context', default='', help_text='Required. Describe what circumstances lead you to this point.', verbose_name='Decision context')),
                ('Project Link', models.TextField(blank=True, db_column='projectLink', help_text='Optional. Link to jira project', verbose_name='Project Link')),
                ('When status was changed', models.DateTimeField(auto_now=True, db_column='statusChangedAt', help_text='When status was changed', null=True, verbose_name='When status was changed')),
            ],
        ),
        migrations.CreateModel(
            name='Influence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('description_fwd', models.TextField(db_column='influence_fwd', help_text='Required. Description on influence .', verbose_name='Influence Forward')),
                ('description_back', models.TextField(db_column='influence_back', help_text='Required. Description on influence .', verbose_name='Influence Backward')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InfluenceADR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changedAt', models.DateTimeField(auto_now_add=True, db_column='changedAt')),
                ('inf_adr', models.ForeignKey(db_column='inf_adr', on_delete=django.db.models.deletion.PROTECT, related_name='inf_adr', to='adr_ui.adr', verbose_name='Affected ADR')),
                ('influence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adr_ui.influence')),
                ('src_adr', models.ForeignKey(db_column='src_adr', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='src_adr', to='adr_ui.adr', verbose_name='Source ADR')),
            ],
        ),
        migrations.AddField(
            model_name='adr',
            name='Affected solutions',
            field=models.ManyToManyField(db_column='affects', help_text='Required. Affected systems. Could be ALL, None or some in between', to='adr_ui.system', verbose_name='Affected solutions'),
        ),
        migrations.AddField(
            model_name='adr',
            name='influence',
            field=models.ManyToManyField(through='adr_ui.InfluenceADR', to='adr_ui.adr'),
        ),
    ]
