# Generated by Django 4.0.5 on 2022-06-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr_ui', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adr',
            name='affects',
        ),
        migrations.RemoveField(
            model_name='adr',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='adr',
            name='projectLink',
        ),
        migrations.AddField(
            model_name='adr',
            name='Affected solutions',
            field=models.ManyToManyField(db_column='affects', help_text='Required. Affected systems. Could be ALL, None or some in between', to='adr_ui.system', verbose_name='Affected solutions'),
        ),
        migrations.AddField(
            model_name='adr',
            name='Decision context',
            field=models.TextField(db_column='context', default='', help_text='Required. Describe what circumstances lead you to this point.', verbose_name='Decision context'),
        ),
        migrations.AddField(
            model_name='adr',
            name='Project Link',
            field=models.TextField(blank=True, db_column='projectLink', help_text='Optional. Link to jira project', verbose_name='Project Link'),
        ),
        migrations.AddField(
            model_name='adr',
            name='When ADR was created',
            field=models.DateTimeField(auto_now=True, db_column='createdAt', help_text='Required. First date of consideration', null=True, verbose_name='When ADR was created'),
        ),
        migrations.AddField(
            model_name='adr',
            name='When status was changed',
            field=models.DateTimeField(auto_now=True, db_column='statusChangedAt', help_text='Required. Affected systems. Could be ALL, None or some in between', null=True, verbose_name='When status was changed'),
        ),
    ]
