# Generated by Django 4.0.5 on 2022-06-11 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adr_ui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adr',
            name='Decision status',
            field=models.ForeignKey(db_column='status', default='', help_text='Required. Current status of the decision. Could be changed over time', on_delete=django.db.models.deletion.PROTECT, to='adr_ui.status', verbose_name='Decision status'),
        ),
        migrations.AddField(
            model_name='adr',
            name='Effects',
            field=models.TextField(db_column='effects', default='', help_text='Required. Describe either effects on previous or future decisions', verbose_name='Effects. Both positive and negative'),
        ),
        migrations.AddField(
            model_name='adr',
            name='decision',
            field=models.TextField(db_column='decision', default='', help_text='Required. Describe how do you overcome the obstracle111.', verbose_name='Decision'),
        ),
    ]
