# Generated by Django 4.0.5 on 2022-06-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr_ui', '0003_alter_adr_when adr was created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adr',
            name='Project Link',
            field=models.TextField(blank=True, db_column='projectLink', help_text='Optional. Link to jira project', null=True, verbose_name='Project Link'),
        ),
        migrations.AlterField(
            model_name='adr',
            name='When status was changed',
            field=models.DateTimeField(auto_now=True, db_column='statusChangedAt', help_text='When status was changed', null=True, verbose_name='When status was changed'),
        ),
    ]
