# Generated by Django 4.0.5 on 2022-06-11 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adr_ui', '0003_rename_decision_adr_decision'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='influenceadr',
            unique_together={('src_adr', 'influence', 'inf_adr')},
        ),
    ]
