# Generated by Django 4.0.5 on 2022-06-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adr_ui', '0004_alter_adr_project link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Influence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('Influence Forward', models.TextField(db_column='influence_fwd', help_text='Required. Description on influence .', verbose_name='Influence Forward')),
                ('Influence Backward', models.TextField(db_column='influence_back', help_text='Required. Description on influence .', verbose_name='Influence Backward')),
            ],
        ),
        migrations.RemoveField(
            model_name='adr',
            name='When ADR was created',
        ),
        migrations.AddField(
            model_name='adr',
            name='adrCreatedAt',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt', help_text='Required. First date of consideration', null=True, verbose_name='When ADR was created'),
        ),
    ]
